version: '3.7'
# DevelopMent
services:
  redis:
    container_name: redis
    image: redis:latest
    hostname: 127.0.0.1
    ports:
      - "6379:6379"
    restart: always
    command: redis-server


  moae-blog:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    image: moae-blog
    container_name: moae-blog
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Seoul